### ISSUE TITLE
Edit (Backward compatibility, 3.1.3 -> 3.2.1)

### ISSUE THREAD

**Issue by mah00r** [foobuzz/todo#16]
After I updated from version 3.1.3 to 3.2.1 I get this error on `todo edit ..`:

```
Traceback (most recent call last):
  File "/Users/blaw_blaw/Library/Python/3.7/bin/todo", line 8, in <module>
    sys.exit(main())
  File "/Users/blaw_blaw/Library/Python/3.7/lib/python/site-packages/todo/todo.py", line 128, in main
    result = dispatch(args, daccess)
  File "/Users/blaw_blaw/Library/Python/3.7/lib/python/site-packages/todo/todo.py", line 396, in dispatch
    return DISPATCHER[args['command']](args, daccess)
  File "/Users/blaw_blaw/Library/Python/3.7/lib/python/site-packages/todo/todo.py", line 218, in edit_task
    can_edit = daccess.take_editing_lock(tid)
  File "/Users/blaw_blaw/Library/Python/3.7/lib/python/site-packages/todo/data_access.py", line 653, in take_editing_lock
    """, (tid,))
sqlite3.OperationalError: no such column: editing
```
It seems that the schema of data.sqlite is changed in the new version without updating the old database.

**Comment by mah00r** [comment]
Found out that on migrating the old database, I did not copy the version file in the data directory. Issue resolved.
