### ISSUE TITLE
 No such file or directory

### ISSUE THREAD

**Issue by julianofischer** [foobuzz/todo#9]
```
Traceback (most recent call last):
  File "/home/juliano/.local/bin/todo", line 11, in <module>
    sys.exit(main())
  File "/home/juliano/.local/lib/python3.6/site-packages/todo/todo.py", line 154, in main
    current_version = get_installed_version()
  File "/home/juliano/.local/lib/python3.6/site-packages/todo/todo.py", line 168, in get_installed_version
    with open(VERSION_PATH, 'w') as version_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/juliano/.toduh/version'
```

**Comment by foobuzz** [comment]
Fixed on version 3.1.2.

Thanks for the report.
